"""CLI entry point with argument parsing and config loading."""

# Import standard library modules: argument parsing, package metadata,
# glob expansion, and system utilities
import argparse
import glob as glob_module
import sys
from importlib.metadata import PackageNotFoundError, version

# Import package modules for image renaming logic and configuration
from . import config, renamer

# Define the package name for version lookup
_PACKAGE_NAME = "ai-image-renamer"

# Define a fallback version string for when package metadata is unavailable
_FALLBACK_VERSION = "1.5.0"


def _get_version() -> str:
    """Return the installed package version, or a source-tree fallback."""
    # Attempt to retrieve the installed package version from metadata
    try:
        return version(_PACKAGE_NAME)
    # Fall back to the hardcoded version if the package is not installed
    except PackageNotFoundError:
        return _FALLBACK_VERSION


def main():
    """Run the AI Image Renamer CLI application.

    This function orchestrates the CLI workflow:
    1. Load the user config file (~/.config/ai-image-renamer-cli/.env)
    2. Keep exported environment variables ahead of that file
    3. Create and configure the argument parser
    4. Parse command-line arguments
    5. Instantiate ImageRenamer to process the images

    The function is designed to be called as the script entry point,
    configured in pyproject.toml under [project.scripts].

    Command-Line Arguments:
        Positional Arguments:
            image_paths: One or more paths to image files to rename
                        Accepts: .jpg, .jpeg, .png, .webp, .gif, etc.
                        At least one path is required (nargs='+')

        Optional Arguments:
            --words, -w N: Number of words in the generated filename
                          Range: 1-50 (validated by argparse choices)
                          Default: From the user config DEFAULT_WORD_COUNT (falls back to 6)
                          Example: -w 3 produces shorter filenames

            --api-key KEY: Groq API key for this invocation.
                          Overrides the exported GROQ_API_KEY and the user config.

            --model MODEL: Groq model to use for image analysis.
                          Overrides MODEL in the user config.
                          Default: qwen/qwen3.8-27b

            --version, -v: Display the package version and exit
                          Example: rename_images -v
                                        Output: rename_images 1.5.0

            --help, -h: Show usage information and exit
                        Automatically generated by argparse

    Returns:
        None: This function performs side effects (file renames) but
              returns nothing. Exit codes:
              - 0: Success (implicit)
              - Non-zero: Exception occurred (propagates)

    Raises:
        RuntimeError: If GROQ_API_KEY is not set (from utils.get_words)
        FileNotFoundError: If specified image file does not exist
        Exception: Any underlying exception propagates to CLI

    Configuration:
        User config: ~/.config/ai-image-renamer-cli/.env
                     ($XDG_CONFIG_HOME/ai-image-renamer-cli/.env when set).
                     Auto-generated with comments on first run if missing.
                     Editable, and kept across pip and pipx reinstalls.

        GROQ_API_KEY: Exported environment variable for the API key.
                     It overrides the same key in the user config file.
                     A shell assignment without export is not visible here.

    Example Usage:
        Command line:

        $ rename_images vacation.jpg family.png
        Processing vacation.jpg...
        Renamed vacation.jpg to /photos/sunny-beach-palm-trees.jpg
        Processing family.png...
        Renamed family.png to /photos/happy-family-portrait.png

        $ rename_images -w 3 cat.jpg
        Processing cat.jpg...
        Renamed cat.jpg to /photos/orange-cat-sleeping.jpg

        $ rename_images -v
        rename_images 1.5.0

    Note:
        The function uses argparse's built-in error handling:
        - Invalid arguments show help and exit with error code
        - --version and --help exit early without processing
        - No explicit return code; exceptions propagate naturally

    """
    # Load the user config file. Exported variables are left in place.
    config.load_environment()

    # Determine the default word count from config (falls back to 6)
    _word_count_raw = config.get("DEFAULT_WORD_COUNT", "6")
    try:
        _default_words = int(_word_count_raw)
        if not 1 <= _default_words <= 50:
            raise ValueError
    except (ValueError, TypeError):
        print(
            f"Invalid DEFAULT_WORD_COUNT '{_word_count_raw}' in {config.config_path()}. Using 6.",
            file=sys.stderr,
        )
        _default_words = 6

    # Create the argument parser with program name, description, and epilog
    parser = argparse.ArgumentParser(
        prog="rename_images",
        description="AI Image Renamer CLI - Rename images using AI-generated descriptions",
        epilog=(
            "Configuration file:\n"
            f"  {config.config_path()}\n"
            "\n"
            "For more information, visit:\n"
            "  Documentation: https://docs.kolja-nolte.com/ai-image-renamer-cli\n"
            "\n"
            "Get your free API key at: https://console.groq.com/keys"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # Add the --version / -v flag to display the package version and exit
    parser.add_argument(
        "--version",
        "-v",
        action="version",
        version=f"%(prog)s {_get_version()}",
        help="Show the version of ai-image-renamer and exit",
    )

    # Add the --words / -w option to control AI-generated filename length (default from config)
    parser.add_argument(
        "--words",
        "-w",
        default=_default_words,
        help=(
            "Number of words to use in the generated filename. "
            "Shorter filenames are more concise; longer are more descriptive. "
            "(default: %(default)s)"
        ),
        type=int,
        metavar="N",
        choices=range(1, 51),
    )

    # Add the --provider option to select the AI backend per invocation
    parser.add_argument(
        "--provider",
        default=None,
        choices=["groq", "ollama", "openai"],
        help=(
            "AI backend to use: groq (hosted), ollama (local), or openai "
            "(any OpenAI-compatible endpoint). "
            "Overrides PROVIDER in the user config file."
        ),
        type=str,
        metavar="PROVIDER",
    )

    # Add the --api-key option to override the Groq API key per invocation
    parser.add_argument(
        "--api-key",
        default=None,
        help=(
            "Groq API key for this invocation. "
            "Overrides the exported GROQ_API_KEY variable and the user config file. "
            "Get a free key at: https://console.groq.com/keys"
        ),
        type=str,
        metavar="KEY",
    )

    # Add the --model option to override the AI model per invocation
    parser.add_argument(
        "--model",
        default=None,
        help=(
            "Groq model to use for image analysis. "
            "Overrides the GROQ_MODEL environment variable and MODEL in the user config file. "
            "Browse available models at: https://console.groq.com/docs/models"
        ),
        type=str,
        metavar="MODEL",
    )

    # Add the positional image_paths argument (one or more file paths required)
    parser.add_argument(
        "image_paths",
        help=(
            "Path(s) to the image file(s) to be renamed. "
            "Accepts multiple files and glob patterns (e.g. *.png). "
            "Supported formats: JPEG, PNG, WebP, GIF, and others detected by content."
        ),
        action="store",
        type=str,
        nargs="+",
    )

    # Parse command-line arguments from sys.argv into a Namespace object
    args = parser.parse_args()

    # Expand any glob patterns in the image paths (e.g. *.png, /Desktop/*.jpg)
    expanded_paths = []
    for raw_path in args.image_paths:
        matches = glob_module.glob(raw_path)
        if matches:
            expanded_paths.extend(sorted(matches))
        else:
            # No glob match — keep the literal path (it may still be valid)
            expanded_paths.append(raw_path)
    args.image_paths = expanded_paths

    # Define the max number of images allowed per invocation
    max_images = 3

    # Warn and truncate if more than the maximum number of images were provided
    if len(args.image_paths) > max_images:
        too_many_count = len(args.image_paths)
        skipped_paths = args.image_paths[max_images:]
        args.image_paths = args.image_paths[:max_images]

        print(
            f"Only {max_images} images can be renamed at a time (you provided {too_many_count}).",
            file=sys.stderr,
        )
        print(
            "  Processing: " + ", ".join(args.image_paths),
            file=sys.stderr,
        )
        print(
            "  Skipping:   " + ", ".join(skipped_paths),
            file=sys.stderr,
        )

    # Delegate processing to ImageRenamer with the parsed arguments
    renamer.ImageRenamer(args)


# Allow the module to be run directly with `python -m ai_image_renamer.cli`
if __name__ == "__main__":
    main()
