# -*- coding: utf-8 -*-
"""CLI entry point with argument parsing."""

# Import standard library modules: argument parsing, package metadata, and system utilities
import argparse
from importlib.metadata import PackageNotFoundError, version
import sys

# Import package modules for image renaming logic
from . import renamer

# Define the package name for version lookup
_PACKAGE_NAME = "ai-image-renamer"

# Define a fallback version string for when package metadata is unavailable
_FALLBACK_VERSION = "1.2.0"


def _get_version() -> str:
    """Return the installed package version, or a source-tree fallback."""

    # Attempt to retrieve the installed package version from metadata
    try:
        return version(_PACKAGE_NAME)
    # Fall back to the hardcoded version if the package is not installed
    except PackageNotFoundError:
        return _FALLBACK_VERSION


def main():
    """
    Main entry point for the AI Image Renamer CLI application.

    This function orchestrates the CLI workflow:
    1. Load environment variables from .env file (if present)
    2. Create and configure the argument parser
    3. Parse command-line arguments
    4. Instantiate ImageRenamer to process the images

    The function is designed to be called as the script entry point,
    configured in pyproject.toml under [project.scripts].

    Command-Line Arguments:
        Positional Arguments:
            image_paths: One or more paths to image files to rename
                        Accepts: .jpg, .jpeg, .png, .webp, .gif, etc.
                        At least one path is required (nargs='+')

        Optional Arguments:
            --words, -w N: Number of words in the generated filename
                          Range: 1-50 (validated by argparse choices)
                          Default: 6
                          Example: -w 3 produces shorter filenames

            --version, -v: Display the package version and exit
                          Example: rename-images -v
                                        Output: rename-images 1.1.0

            --help, -h: Show usage information and exit
                        Automatically generated by argparse

    Returns:
        None: This function performs side effects (file renames) but
              returns nothing. Exit codes:
              - 0: Success (implicit)
              - Non-zero: Exception occurred (propagates)

    Raises:
        RuntimeError: If GROQ_API_KEY is not set (from utils.get_words)
        FileNotFoundError: If specified image file does not exist
        Exception: Any underlying exception propagates to CLI

    Environment Variables:
        GROQ_API_KEY: Required for AI image analysis
                     Must be set before calling this function
                     Can be in .env file, .bashrc, .zshrc, or exported

    Example Usage:
        Command line:

        $ rename-images vacation.jpg family.png
        Processing vacation.jpg...
        Renamed vacation.jpg to /photos/sunny-beach-palm-trees.jpg
        Processing family.png...
        Renamed family.png to /photos/happy-family-portrait.png

        $ rename-images -w 3 cat.jpg
        Processing cat.jpg...
        Renamed cat.jpg to /photos/orange-cat-sleeping.jpg

        $ rename-images -v
        rename-images 1.1.0

    Note:
        The function uses argparse's built-in error handling:
        - Invalid arguments show help and exit with error code
        - --version and --help exit early without processing
        - No explicit return code; exceptions propagate naturally
    """

    # Import dotenv lazily to avoid requiring it at module import time
    from dotenv import load_dotenv
    # Load environment variables from .env file if present (does not override existing vars)
    load_dotenv()

    # Create the argument parser with program name, description, and epilog
    parser = argparse.ArgumentParser(
        prog="rename-images",
        description="AI Image Renamer CLI - Rename images using AI-generated descriptions",
        epilog=(
            "For more information, visit:\n"
            "  Documentation: https://docs.kolja-nolte.com/ai-image-renamer-cli\n"
            "\n"
            "Get your free API key at: https://console.groq.com/keys"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # Add the --version / -v flag to display the package version and exit
    parser.add_argument(
        '--version', '-v',
        action="version",
        version=f"%(prog)s {_get_version()}",
        help="Show the version of ai-image-renamer and exit"
    )

    # Add the --words / -w option to control AI-generated filename length (default: 6)
    parser.add_argument(
        '--words', '-w',
        default=6,
        help=(
            "Number of words to use in the generated filename. "
            "Shorter filenames are more concise; longer are more descriptive. "
            "(default: %(default)s)"
        ),
        type=int,
        metavar='N',
        choices=range(1, 51),
    )

    # Add the positional image_paths argument (one or more file paths required)
    parser.add_argument(
        'image_paths',
        help=(
            "Path(s) to the image file(s) to be renamed. "
            "Accepts multiple files. "
            "Supported formats: JPEG, PNG, WebP, GIF, and others detected by content."
        ),
        action="store",
        type=str,
        nargs='+'
    )

    # Parse command-line arguments from sys.argv into a Namespace object
    args = parser.parse_args()

    # Define the maximum number of images allowed per invocation
    MAX_IMAGES = 3

    # Warn and truncate if more than the maximum number of images were provided
    if len(args.image_paths) > MAX_IMAGES:
        print(
            f"A maximum of {MAX_IMAGES} images can be processed at once. "
            f"Truncating list from {len(args.image_paths)} to {MAX_IMAGES}.",
            file=sys.stderr,
        )
        args.image_paths = args.image_paths[:MAX_IMAGES]

    # Delegate processing to ImageRenamer with the parsed arguments
    renamer.ImageRenamer(args)


# Allow the module to be run directly with `python -m ai_image_renamer.cli`
if __name__ == '__main__':
    main()
